version: "3.7"
services:
    ray-rllib:
        build:
            context: ./app
            dockerfile: ./Dockerfile
        volumes:
            - ./GymEnv:/app/GymEnv
            - ./Training:/app/Training
        working_dir: /app
        ports:
            - "6379:6379"  # Ray Core
            - "8265:8265"  # Ray Dashboard
            - "8080:8080"  # Ray Monitoring
            - "6006:6006"  # Tensorboard
    prometheus:
        image: prom/prometheus:latest
        depends_on:
            - 'ray-rllib'
        volumes:
            - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana:latest
        depends_on:
            - 'prometheus'
        links:
            - prometheus:promtheus
            - ray-rllib:ray-rllib
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/grafana_data:/var/lib/grafana
        user: "1000"